server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/futurity
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

rabbitmq:
  host: localhost
  virtualhost: "/"
  port: 15672
  username: admin
  password: admin
  exchange: futurity-exchange
  queue: futurity-system-queue
  routing:
   key: product-queue
  reply:
    timeout: 60000
  concurrent:
    consumers: 5
  max:
    concurrent:
      consumers: 5
