server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/futurity
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: guest
    password: guest
    virtualhost: "/"

rabbitmq:
  host: localhost
  virtualhost: "/"
  port: 15672
  username: admin
  password: admin
  exchange: futurity-exchange
  queue: api-queue
  routing:
   key: api-queue
  reply:
    timeout: 60000
  concurrent:
    consumers: 5
  max:
    concurrent:
      consumers: 5

queues:
  user: user-queue
  product: product-queue